name: flutter_powerbi_embed
description: "A Flutter package that uses WebView to seamlessly embed Power BI reports and dashboards in your Flutter applications."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0